//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for constraintType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="constraintType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NO_SINGLE_ELECTRONS"/>
 *     &lt;enumeration value="IS_NOT_AROMATIC"/>
 *     &lt;enumeration value="ATOMCOUNT"/>
 *     &lt;enumeration value="DOUBLEBONDCOUNT"/>
 *     &lt;enumeration value="SINGLEELECTRONCOUNT"/>
 *     &lt;enumeration value="SSSRINGCOUNT"/>
 *     &lt;enumeration value="AROMATICATOMSCOUNT"/>
 *     &lt;enumeration value="HEAVYATOMCOUNT"/>
 *     &lt;enumeration value="STRUCTURE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "constraintType")
@XmlEnum
public enum ConstraintType {

    NO_SINGLE_ELECTRONS,
    IS_NOT_AROMATIC,
    ATOMCOUNT,
    DOUBLEBONDCOUNT,
    SINGLEELECTRONCOUNT,
    SSSRINGCOUNT,
    AROMATICATOMSCOUNT,
    HEAVYATOMCOUNT,
    STRUCTURE;

    public String value() {
        return name();
    }

    public static ConstraintType fromValue(String v) {
        return valueOf(v);
    }

}
