//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inp-kinetics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inp-kinetics">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inp-reaction" type="{}inp-reaction" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="inp-tunneling" type="{}inp-tunneling" minOccurs="0"/>
 *         &lt;element name="rate-coeff" type="{}rate-coeff" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="inp-kinetic-reactive-center" type="{}inp-kinetic-ga-db" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="inp-kinetic-resonance-correction" type="{}inp-kinetic-ga-db" minOccurs="0"/>
 *         &lt;element name="inp-reactive-center-template" type="{}inp-reactive-center-template" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{}kineticsType" />
 *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inp-kinetics", propOrder = {
    "inpReaction",
    "inpTunneling",
    "rateCoeff",
    "inpKineticReactiveCenter",
    "inpKineticResonanceCorrection",
    "inpReactiveCenterTemplate"
})
public class InpKinetics {

    @XmlElement(name = "inp-reaction")
    protected List<InpReaction> inpReaction;
    @XmlElement(name = "inp-tunneling")
    protected InpTunneling inpTunneling;
    @XmlElement(name = "rate-coeff")
    protected List<RateCoeff> rateCoeff;
    @XmlElement(name = "inp-kinetic-reactive-center")
    protected List<InpKineticGaDb> inpKineticReactiveCenter;
    @XmlElement(name = "inp-kinetic-resonance-correction")
    protected InpKineticGaDb inpKineticResonanceCorrection;
    @XmlElement(name = "inp-reactive-center-template")
    protected List<InpReactiveCenterTemplate> inpReactiveCenterTemplate;
    @XmlAttribute(name = "type", required = true)
    protected KineticsType type;
    @XmlAttribute(name = "path")
    protected String path;

    /**
     * Gets the value of the inpReaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inpReaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInpReaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InpReaction }
     * 
     * 
     */
    public List<InpReaction> getInpReaction() {
        if (inpReaction == null) {
            inpReaction = new ArrayList<InpReaction>();
        }
        return this.inpReaction;
    }

    /**
     * Gets the value of the inpTunneling property.
     * 
     * @return
     *     possible object is
     *     {@link InpTunneling }
     *     
     */
    public InpTunneling getInpTunneling() {
        return inpTunneling;
    }

    /**
     * Sets the value of the inpTunneling property.
     * 
     * @param value
     *     allowed object is
     *     {@link InpTunneling }
     *     
     */
    public void setInpTunneling(InpTunneling value) {
        this.inpTunneling = value;
    }

    /**
     * Gets the value of the rateCoeff property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rateCoeff property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRateCoeff().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RateCoeff }
     * 
     * 
     */
    public List<RateCoeff> getRateCoeff() {
        if (rateCoeff == null) {
            rateCoeff = new ArrayList<RateCoeff>();
        }
        return this.rateCoeff;
    }

    public void addRateCoeff(RateCoeff rate){
    	if (rateCoeff == null) {
            rateCoeff = new ArrayList<RateCoeff>();
        }
        this.rateCoeff.add(rate);
    }
    /**
     * Gets the value of the inpKineticReactiveCenter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inpKineticReactiveCenter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInpKineticReactiveCenter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InpKineticGaDb }
     * 
     * 
     */
    public List<InpKineticGaDb> getInpKineticReactiveCenter() {
        if (inpKineticReactiveCenter == null) {
            inpKineticReactiveCenter = new ArrayList<InpKineticGaDb>();
        }
        return this.inpKineticReactiveCenter;
    }

    /**
     * Gets the value of the inpKineticResonanceCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link InpKineticGaDb }
     *     
     */
    public InpKineticGaDb getInpKineticResonanceCorrection() {
        return inpKineticResonanceCorrection;
    }

    /**
     * Sets the value of the inpKineticResonanceCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link InpKineticGaDb }
     *     
     */
    public void setInpKineticResonanceCorrection(InpKineticGaDb value) {
        this.inpKineticResonanceCorrection = value;
    }

    /**
     * Gets the value of the inpReactiveCenterTemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inpReactiveCenterTemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInpReactiveCenterTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InpReactiveCenterTemplate }
     * 
     * 
     */
    public List<InpReactiveCenterTemplate> getInpReactiveCenterTemplate() {
        if (inpReactiveCenterTemplate == null) {
            inpReactiveCenterTemplate = new ArrayList<InpReactiveCenterTemplate>();
        }
        return this.inpReactiveCenterTemplate;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link KineticsType }
     *     
     */
    public KineticsType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link KineticsType }
     *     
     */
    public void setType(KineticsType value) {
        this.type = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
