//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inp-reactive-center complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inp-reactive-center">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inp-atom-constraint" type="{}inp-constraint" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="inp-non-reactive-center" type="{}inp-non-reactive-center" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" use="required" type="{}symbolType" />
 *       &lt;attribute name="smarts" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="neighbour" type="{}symbolType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inp-reactive-center", propOrder = {
    "inpAtomConstraint",
    "inpNonReactiveCenter"
})
public class InpReactiveCenter {

    @XmlElement(name = "inp-atom-constraint")
    protected List<InpConstraint> inpAtomConstraint;
    @XmlElement(name = "inp-non-reactive-center")
    protected InpNonReactiveCenter inpNonReactiveCenter;
    @XmlAttribute(name = "symbol", required = true)
    protected String symbol;
    @XmlAttribute(name = "smarts", required = true)
    protected String smarts;
    @XmlAttribute(name = "neighbour")
    protected String neighbour;

    /**
     * Gets the value of the inpAtomConstraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inpAtomConstraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInpAtomConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InpConstraint }
     * 
     * 
     */
    public List<InpConstraint> getInpAtomConstraint() {
        if (inpAtomConstraint == null) {
            inpAtomConstraint = new ArrayList<InpConstraint>();
        }
        return this.inpAtomConstraint;
    }

    /**
     * Gets the value of the inpNonReactiveCenter property.
     * 
     * @return
     *     possible object is
     *     {@link InpNonReactiveCenter }
     *     
     */
    public InpNonReactiveCenter getInpNonReactiveCenter() {
        return inpNonReactiveCenter;
    }

    /**
     * Sets the value of the inpNonReactiveCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link InpNonReactiveCenter }
     *     
     */
    public void setInpNonReactiveCenter(InpNonReactiveCenter value) {
        this.inpNonReactiveCenter = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the smarts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmarts() {
        return smarts;
    }

    /**
     * Sets the value of the smarts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmarts(String value) {
        this.smarts = value;
    }

    /**
     * Gets the value of the neighbour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeighbour() {
        return neighbour;
    }

    /**
     * Sets the value of the neighbour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeighbour(String value) {
        this.neighbour = value;
    }

}
