//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inp-reaction-family complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inp-reaction-family">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bimolecular" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="inp-recipe" type="{}inp-recipe" minOccurs="0"/>
 *         &lt;element name="inp-reactant" type="{}inp-reactant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="inp-kinetics" type="{}inp-kinetics" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inp-reaction-family", propOrder = {
    "bimolecular",
    "inpRecipe",
    "inpReactant",
    "inpKinetics"
})
public class InpReactionFamily {

    protected boolean bimolecular;
    @XmlElement(name = "inp-recipe")
    protected InpRecipe inpRecipe;
    @XmlElement(name = "inp-reactant")
    protected List<InpReactant> inpReactant;
    @XmlElement(name = "inp-kinetics")
    protected InpKinetics inpKinetics;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the bimolecular property.
     * 
     */
    public boolean isBimolecular() {
        return bimolecular;
    }

    /**
     * Sets the value of the bimolecular property.
     * 
     */
    public void setBimolecular(boolean value) {
        this.bimolecular = value;
    }

    /**
     * Gets the value of the inpRecipe property.
     * 
     * @return
     *     possible object is
     *     {@link InpRecipe }
     *     
     */
    public InpRecipe getInpRecipe() {
        return inpRecipe;
    }

    /**
     * Sets the value of the inpRecipe property.
     * 
     * @param value
     *     allowed object is
     *     {@link InpRecipe }
     *     
     */
    public void setInpRecipe(InpRecipe value) {
        this.inpRecipe = value;
    }

    /**
     * Gets the value of the inpReactant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inpReactant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInpReactant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InpReactant }
     * 
     * 
     */
    public List<InpReactant> getInpReactant() {
        if (inpReactant == null) {
            inpReactant = new ArrayList<InpReactant>();
        }
        return this.inpReactant;
    }
    
    /**Add a new reactant to the family. Create new list if none exists.
     * 
     * @param reactant
     */
    public void addInpReactant(InpReactant reactant){
    	if(inpReactant == null){
    		inpReactant = new ArrayList<InpReactant>();
    	}
    	
    	inpReactant.add(reactant);
    }

    /**
     * Gets the value of the inpKinetics property.
     * 
     * @return
     *     possible object is
     *     {@link InpKinetics }
     *     
     */
    public InpKinetics getInpKinetics() {
        return inpKinetics;
    }

    /**
     * Sets the value of the inpKinetics property.
     * 
     * @param value
     *     allowed object is
     *     {@link InpKinetics }
     *     
     */
    public void setInpKinetics(InpKinetics value) {
        this.inpKinetics = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

	public void setInpReactant(List<InpReactant> reactants) {
		this.inpReactant	=	reactants;
		
	}

}
