//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inp-reaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inp-reaction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reactant" type="{}reactant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="product" type="{}product" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rate-coeff" type="{}rate-coeff"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inp-reaction", propOrder = {
    "reactant",
    "product",
    "rateCoeff"
})
public class InpReaction {

    protected List<Reactant> reactant;
    protected List<Product> product;
    @XmlElement(name = "rate-coeff", required = true)
    protected RateCoeff rateCoeff;

    /**
     * Gets the value of the reactant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reactant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReactant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reactant }
     * 
     * 
     */
    public List<Reactant> getReactant() {
        if (reactant == null) {
            reactant = new ArrayList<Reactant>();
        }
        return this.reactant;
    }

    /**
     * Gets the value of the product property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the product property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Product }
     * 
     * 
     */
    public List<Product> getProduct() {
        if (product == null) {
            product = new ArrayList<Product>();
        }
        return this.product;
    }

    /**
     * Gets the value of the rateCoeff property.
     * 
     * @return
     *     possible object is
     *     {@link RateCoeff }
     *     
     */
    public RateCoeff getRateCoeff() {
        return rateCoeff;
    }

    /**
     * Sets the value of the rateCoeff property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateCoeff }
     *     
     */
    public void setRateCoeff(RateCoeff value) {
        this.rateCoeff = value;
    }

}
