//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inp-reactant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inp-reactant">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inp-reactive-center" type="{}inp-reactive-center" maxOccurs="unbounded"/>
 *         &lt;element name="inp-molecule-constraint" type="{}inp-constraint" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="smarts" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inp-reactant", propOrder = {
    "inpReactiveCenter",
    "inpMoleculeConstraint"
})
public class InpReactant {

    @XmlElement(name = "inp-reactive-center", required = true)
    protected List<InpReactiveCenter> inpReactiveCenter;
    @XmlElement(name = "inp-molecule-constraint")
    protected List<InpConstraint> inpMoleculeConstraint;
    @XmlAttribute(name = "value", required = true)
    protected int value;
    @XmlAttribute(name = "smarts", required = true)
    protected String smarts;

    /**
     * Gets the value of the inpReactiveCenter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inpReactiveCenter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInpReactiveCenter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InpReactiveCenter }
     * 
     * 
     */
    public List<InpReactiveCenter> getInpReactiveCenter() {
        if (inpReactiveCenter == null) {
            inpReactiveCenter = new ArrayList<InpReactiveCenter>();
        }
        return this.inpReactiveCenter;
    }
    
    public void addInpReactiveCenter(InpReactiveCenter reactiveCenter){
    	if (inpReactiveCenter == null) {
            inpReactiveCenter = new ArrayList<InpReactiveCenter>();
        }
        this.inpReactiveCenter.add(reactiveCenter);
    }

    /**
     * Gets the value of the inpMoleculeConstraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inpMoleculeConstraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInpMoleculeConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InpConstraint }
     * 
     * 
     */
    public List<InpConstraint> getInpMoleculeConstraint() {
        if (inpMoleculeConstraint == null) {
            inpMoleculeConstraint = new ArrayList<InpConstraint>();
        }
        return this.inpMoleculeConstraint;
    }
    
    public void addInpMoleculeConstraint(InpConstraint constraint){
    	if (inpMoleculeConstraint == null) {
            inpMoleculeConstraint = new ArrayList<InpConstraint>();
        }
        this.inpMoleculeConstraint.add(constraint);
    }

    /**
     * Gets the value of the value property.
     * 
     */
    public int getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(int value) {
        this.value = value;
    }

    /**
     * Gets the value of the smarts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmarts() {
        return smarts;
    }

    /**
     * Sets the value of the smarts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmarts(String value) {
        this.smarts = value;
    }

}
