//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inp-steric-relation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inp-steric-relation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inp-substituent" type="{}inp-substituent" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="stereo" use="required" type="{}stereoType" />
 *       &lt;attribute name="type" use="required" type="{}stericType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inp-steric-relation", propOrder = {
    "inpSubstituent"
})
public class InpStericRelation {

    @XmlElement(name = "inp-substituent", required = true)
    protected List<InpSubstituent> inpSubstituent;
    @XmlAttribute(name = "stereo", required = true)
    protected StereoType stereo;
    @XmlAttribute(name = "type", required = true)
    protected StericType type;

    /**
     * Gets the value of the inpSubstituent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inpSubstituent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInpSubstituent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InpSubstituent }
     * 
     * 
     */
    public List<InpSubstituent> getInpSubstituent() {
        if (inpSubstituent == null) {
            inpSubstituent = new ArrayList<InpSubstituent>();
        }
        return this.inpSubstituent;
    }

    /**
     * Gets the value of the stereo property.
     * 
     * @return
     *     possible object is
     *     {@link StereoType }
     *     
     */
    public StereoType getStereo() {
        return stereo;
    }

    /**
     * Sets the value of the stereo property.
     * 
     * @param value
     *     allowed object is
     *     {@link StereoType }
     *     
     */
    public void setStereo(StereoType value) {
        this.stereo = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link StericType }
     *     
     */
    public StericType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link StericType }
     *     
     */
    public void setType(StericType value) {
        this.type = value;
    }

}
