//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inp-transformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inp-transformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{}transformationType" />
 *       &lt;attribute name="centers" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inp-transformation")
public class InpTransformation {

    @XmlAttribute(name = "type", required = true)
    protected TransformationType type;
    @XmlAttribute(name = "centers", required = true)
    protected String centers;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TransformationType }
     *     
     */
    public TransformationType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransformationType }
     *     
     */
    public void setType(TransformationType value) {
        this.type = value;
    }

    /**
     * Gets the value of the centers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCenters() {
        return centers;
    }

    /**
     * Sets the value of the centers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCenters(String value) {
        this.centers = value;
    }

}
