//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for kineticsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="kineticsType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ARRHENIUS"/>
 *     &lt;enumeration value="AB_INITIO"/>
 *     &lt;enumeration value="EVANS_POLANYI"/>
 *     &lt;enumeration value="GROUP_ADDITIVITY"/>
 *     &lt;enumeration value="REVERSE"/>
 *     &lt;enumeration value="BLOWERS_MASEL"/>
 *     &lt;enumeration value="TEMP_INDEPENDENT_RATE"/>
 *     &lt;enumeration value="LIBRARY"/>
 *     &lt;enumeration value="RATE_RULE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "kineticsType")
@XmlEnum
public enum KineticsType {

    ARRHENIUS,
    AB_INITIO,
    EVANS_POLANYI,
    GROUP_ADDITIVITY,
    REVERSE,
    BLOWERS_MASEL,
    TEMP_INDEPENDENT_RATE,
    LIBRARY,
    RATE_RULE;

    public String value() {
        return name();
    }

    public static KineticsType fromValue(String v) {
        return valueOf(v);
    }

}
