//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the reactorcore.readers.xmlClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Config_QNAME = new QName("", "config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: reactorcore.readers.xmlClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link Reactant }
     * 
     */
    public Reactant createReactant() {
        return new Reactant();
    }

    /**
     * Create an instance of {@link InpTunneling }
     * 
     */
    public InpTunneling createInpTunneling() {
        return new InpTunneling();
    }

    /**
     * Create an instance of {@link InpChiralCenter }
     * 
     */
    public InpChiralCenter createInpChiralCenter() {
        return new InpChiralCenter();
    }

    /**
     * Create an instance of {@link InpKineticGaDb }
     * 
     */
    public InpKineticGaDb createInpKineticGaDb() {
        return new InpKineticGaDb();
    }

    /**
     * Create an instance of {@link InpStericRelation }
     * 
     */
    public InpStericRelation createInpStericRelation() {
        return new InpStericRelation();
    }

    /**
     * Create an instance of {@link InpKinetics }
     * 
     */
    public InpKinetics createInpKinetics() {
        return new InpKinetics();
    }

    /**
     * Create an instance of {@link InpSubstituent }
     * 
     */
    public InpSubstituent createInpSubstituent() {
        return new InpSubstituent();
    }

    /**
     * Create an instance of {@link InpReaction }
     * 
     */
    public InpReaction createInpReaction() {
        return new InpReaction();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link InpReactiveCenter }
     * 
     */
    public InpReactiveCenter createInpReactiveCenter() {
        return new InpReactiveCenter();
    }

    /**
     * Create an instance of {@link InpNonReactiveCenter }
     * 
     */
    public InpNonReactiveCenter createInpNonReactiveCenter() {
        return new InpNonReactiveCenter();
    }

    /**
     * Create an instance of {@link InpConstraint }
     * 
     */
    public InpConstraint createInpConstraint() {
        return new InpConstraint();
    }

    /**
     * Create an instance of {@link InpKineticGroup }
     * 
     */
    public InpKineticGroup createInpKineticGroup() {
        return new InpKineticGroup();
    }

    /**
     * Create an instance of {@link InpReactiveCenterTemplate }
     * 
     */
    public InpReactiveCenterTemplate createInpReactiveCenterTemplate() {
        return new InpReactiveCenterTemplate();
    }

    /**
     * Create an instance of {@link InpTransformation }
     * 
     */
    public InpTransformation createInpTransformation() {
        return new InpTransformation();
    }

    /**
     * Create an instance of {@link InpReactionFamily }
     * 
     */
    public InpReactionFamily createInpReactionFamily() {
        return new InpReactionFamily();
    }

    /**
     * Create an instance of {@link InpRecipe }
     * 
     */
    public InpRecipe createInpRecipe() {
        return new InpRecipe();
    }

    /**
     * Create an instance of {@link RateCoeff }
     * 
     */
    public RateCoeff createRateCoeff() {
        return new RateCoeff();
    }

    /**
     * Create an instance of {@link InpReactant }
     * 
     */
    public InpReactant createInpReactant() {
        return new InpReactant();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Config }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "config")
    public JAXBElement<Config> createConfig(Config value) {
        return new JAXBElement<Config>(_Config_QNAME, Config.class, null, value);
    }

}
