//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rate-coeff complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rate-coeff">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inp-steric-relation" type="{}inp-steric-relation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="A" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="N" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="Ea" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="wbwf" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="ep-constant" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="ep-alpha" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="vp" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="comments" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rate-coeff", propOrder = {
    "inpStericRelation"
})
public class RateCoeff {

    @XmlElement(name = "inp-steric-relation")
    protected List<InpStericRelation> inpStericRelation;
    @XmlAttribute(name = "A", required = true)
    protected double a;
    @XmlAttribute(name = "N")
    protected Double n;
    @XmlAttribute(name = "Ea")
    protected Double ea;
    @XmlAttribute(name = "wbwf")
    protected Double wbwf;
    @XmlAttribute(name = "ep-constant")
    protected Double epConstant;
    @XmlAttribute(name = "ep-alpha")
    protected Double epAlpha;
    @XmlAttribute(name = "vp")
    protected Double vp;
    @XmlAttribute(name = "comments")
    protected String comments;

    /**
     * Gets the value of the inpStericRelation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inpStericRelation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInpStericRelation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InpStericRelation }
     * 
     * 
     */
    public List<InpStericRelation> getInpStericRelation() {
        if (inpStericRelation == null) {
            inpStericRelation = new ArrayList<InpStericRelation>();
        }
        return this.inpStericRelation;
    }

    /**
     * Gets the value of the a property.
     * 
     */
    public double getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     */
    public void setA(double value) {
        this.a = value;
    }

    /**
     * Gets the value of the n property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getN() {
    	
    	if(n == null)
    		return 0.0;
        return n;
    }

    /**
     * Sets the value of the n property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setN(Double value) {
        this.n = value;
    }

    /**
     * Gets the value of the ea property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEa() {
        return ea;
    }

    /**
     * Sets the value of the ea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEa(Double value) {
        this.ea = value;
    }

    /**
     * Gets the value of the wbwf property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWbwf() {
        return wbwf;
    }

    /**
     * Sets the value of the wbwf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWbwf(Double value) {
        this.wbwf = value;
    }

    /**
     * Gets the value of the epConstant property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEpConstant() {
        return epConstant;
    }

    /**
     * Sets the value of the epConstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEpConstant(Double value) {
        this.epConstant = value;
    }

    /**
     * Gets the value of the epAlpha property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEpAlpha() {
        return epAlpha;
    }

    /**
     * Sets the value of the epAlpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEpAlpha(Double value) {
        this.epAlpha = value;
    }

    /**
     * Gets the value of the vp property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVp() {
        return vp;
    }

    /**
     * Sets the value of the vp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVp(Double value) {
        this.vp = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
