//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 02:50:12 PM CET 
//


package io.readers.xmlClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transformationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="transformationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INCREASE_BOND"/>
 *     &lt;enumeration value="DECREASE_BOND"/>
 *     &lt;enumeration value="FORM_BOND"/>
 *     &lt;enumeration value="BREAK_BOND"/>
 *     &lt;enumeration value="GAIN_RADICAL"/>
 *     &lt;enumeration value="LOSE_RADICAL"/>
 *     &lt;enumeration value="GAIN_CHARGE"/>
 *     &lt;enumeration value="LOSE_CHARGE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "transformationType")
@XmlEnum
public enum TransformationType {

    INCREASE_BOND,
    DECREASE_BOND,
    FORM_BOND,
    BREAK_BOND,
    GAIN_RADICAL,
    LOSE_RADICAL,
    GAIN_CHARGE,
    LOSE_CHARGE;

    public String value() {
        return name();
    }

    public static TransformationType fromValue(String v) {
        return valueOf(v);
    }

}
